### PR TITLE
[add] full working example and comments

### LINKED ISSUE #91: Upload Failure - 403 Error returned
Upload failed in step:
  
 Output.
```
Run gavv/pull-request-artifacts@v1.0.0
Artifacts repo: eriknyk/my-demo-repo
Artifacts branch: artifacts
(node:2273) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
GET /repos/eriknyk/towbook-android-experimental/contents/?ref=artifacts - 404 in 223ms
Uploading file pr1-towbook-2.9.37-30365.apk (first time)
PUT /repos/eriknyk/my-demo-repo/contents/pr1-my-demo-repo-2.9.37-30365.apk - 403 in [19](https://github.com/eriknyk/my-demo-repo/actions/runs/4178992925/jobs/7238431735#step:9:19)92ms

Error: Resource not accessible by integration
```

I have my action configured as following:

```
name: "Android apk build from Pull Request #"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  build:
    name: build-publish-job
    runs-on: ubuntu-latest
    steps:
     - name: Pull request artifacts
        if: ${{ github.event_name == 'pull_request' }}
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: artifacts
          artifacts: |
            ${{ env.OUTPUT_PATH }}/apk/release/2.9.37-30365.apk
```

### PR DESCRIPTION
**Pull request by rvalitov**
Fixes #91 
There are 2 problems:
- missing GitHub permissions
- the branch is protected or has rules for PR that do not allow to upload artifacts

The information above is missing from the README, therefore the action does not work.
I made a full working example and added info how to resolve the issues above.

### CODE REVIEW

**Comment by rvalitov** [comment]
@gavv ping

**Comment by gavv** [comment]
> @gavv ping

Hi, thanks for PRs and sorry for delay! I hope I'll have a chance to look at them closely on this week, currently being a bit busy on other projects.

**Comment by rvalitov** [comment]
great thanks!

**Comment by gavv** [comment]
Thanks! Small follow-up: 8be64fc1aec22eed67ca9e8927f75f9ca510db74

**Pull request merged**
